### ISSUE TITLE
Pagination does not work properly

### ISSUE THREAD

**Issue by opsdep** [nansencenter/django-geo-spaas-adas-viewer#9]
If the user do some filtering and see the result, as soon as s/he click on the next link of Paginator in order to go to the paginated page, the filter is removed and the next page of all datasets are shown. This filtering action must persist untill the user refresh the webpage.

For example the user filter the results and this is what s/he sees:
![image](https://user-images.githubusercontent.com/62345618/86101880-26c02a00-babb-11ea-84cf-bcbd90bdce34.png)

After s/he click on the next bottun, the below figure is shown which is wrong in the number of datasets:
![image](https://user-images.githubusercontent.com/62345618/86101935-3770a000-babb-11ea-804e-75e3494752f0.png)

 It ought to be corrected preferably by the developer of pagination.

**Comment by akorosov** [comment]
The issue doesn't belong here.
Reopening in django-geo-spaas
